#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Patches the azd-ai-starter-basic main.bicep to include the workshop SWA module.

.DESCRIPTION
    Run AFTER `azd init -t Azure-Samples/azd-ai-starter-basic -e dev --no-prompt`
    (or after `azd init -e dev` from inside a workshop Track folder that already
    ships a synced copy of starter-basic infra) and BEFORE `azd up`.
    Idempotent — second run is a no-op.

    What it does:
      1. Copies workshop/infra/swa.bicep into the student's ./infra/ so the
         relative module path is short and self-contained.
      2. Appends a `module workshopSwa './swa.bicep'` block + outputs to the
         student's ./infra/main.bicep.
      3. Wires the App Insights name + a per-run name suffix from azd env
         (`WORKSHOP_NAME_SUFFIX`, generated by preflight.ps1) so the SWA
         survives global-namespace collisions on retries.

.PARAMETER MainBicep
    Path to the student's infra/main.bicep (default: ./infra/main.bicep).

.PARAMETER WorkshopSwaBicep
    Path to the workshop-supplied swa.bicep that should be copied into ./infra/
    (default: auto-detected relative to this script).

.EXAMPLE
    cd workshop/track-A
    ../workshop-scripts/install-swa-patch.ps1
#>
[CmdletBinding()]
param(
    [string]$MainBicep = ".\infra\main.bicep",
    [string]$WorkshopSwaBicep
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $MainBicep)) {
    Write-Host "❌ $MainBicep not found. Run from a folder where 'azd init -t azd-ai-starter-basic' has been run." -ForegroundColor Red
    exit 1
}

if (-not $WorkshopSwaBicep) {
    $WorkshopSwaBicep = Join-Path $PSScriptRoot "..\infra\swa.bicep"
}
if (-not (Test-Path $WorkshopSwaBicep)) {
    Write-Host "❌ Could not locate workshop swa.bicep at $WorkshopSwaBicep." -ForegroundColor Red
    exit 1
}

# 1. Copy swa.bicep into the student's infra/ for a short relative import path.
$infraDir = Split-Path -Parent $MainBicep
$localSwaBicep = Join-Path $infraDir "swa.bicep"
Copy-Item -Force $WorkshopSwaBicep $localSwaBicep
Write-Host "✅ Copied swa.bicep -> $localSwaBicep" -ForegroundColor Green

# 2. Append the module reference to main.bicep (idempotent).
$content = Get-Content $MainBicep -Raw

if ($content -match "module workshopSwa") {
    Write-Host "✅ SWA module already patched into $MainBicep — nothing to do." -ForegroundColor Green
    exit 0
}

# The starter's main.bicep is subscription-scoped; resources live in `rg` and
# App Insights is wired via `aiProject.outputs.APPLICATIONINSIGHTS_RESOURCE_ID`
# (no `applicationInsightsName` output is exposed). Derive the name client-side.
$patch = @"


// =========================================================================
// Workshop add-on: Static Web App for the observability dashboard (Lab 4).
// Patched in by workshop-scripts/install-swa-patch.ps1.
//
// Naming-conflict notes:
//   - workshopResourceToken includes RG so different student RGs differ
//     automatically.
//   - workshopNameSuffix is a per-run salt from azd env WORKSHOP_NAME_SUFFIX
//     (generated by workshop-scripts/preflight.ps1) so retries in the same RG
//     after a botched teardown still get a fresh SWA name.
// =========================================================================
@description('Optional per-run salt to avoid global-namespace name collisions on retries.')
param workshopNameSuffix string = ''

var workshopResourceToken = uniqueString(subscription().id, resourceGroupName, location)
var workshopAppInsightsResourceId = useExistingAiProject ? existingAiProject.outputs.APPLICATIONINSIGHTS_RESOURCE_ID : aiProject.outputs.APPLICATIONINSIGHTS_RESOURCE_ID
var workshopAppInsightsName = last(split(workshopAppInsightsResourceId, '/'))

module workshopSwa './swa.bicep' = {
  scope: rg
  name: 'workshop-swa'
  params: {
    resourceToken: workshopResourceToken
    nameSuffix: workshopNameSuffix
    applicationInsightsName: workshopAppInsightsName
    tags: tags
  }
}

output SWA_URL string = workshopSwa.outputs.swaUrl
output SWA_NAME string = workshopSwa.outputs.swaName
"@

Add-Content -Path $MainBicep -Value $patch -Encoding UTF8
Write-Host "✅ Patched $MainBicep with workshop SWA module." -ForegroundColor Green

# 3. Tell azd to pass WORKSHOP_NAME_SUFFIX into the bicep parameter.
# Starter-basic ships a `parameters.json` under infra/ — append our param.
$parametersFile = Join-Path $infraDir "main.parameters.json"
if (Test-Path $parametersFile) {
    try {
        $params = Get-Content $parametersFile -Raw | ConvertFrom-Json
        if (-not $params.parameters.PSObject.Properties['workshopNameSuffix']) {
            $params.parameters | Add-Member -NotePropertyName 'workshopNameSuffix' -NotePropertyValue ([PSCustomObject]@{ value = '${WORKSHOP_NAME_SUFFIX=}' })
            $params | ConvertTo-Json -Depth 10 | Set-Content -Path $parametersFile -Encoding UTF8
            Write-Host "✅ Wired WORKSHOP_NAME_SUFFIX into $parametersFile." -ForegroundColor Green
        } else {
            Write-Host "ℹ workshopNameSuffix already present in $parametersFile — leaving untouched." -ForegroundColor DarkGray
        }
    } catch {
        Write-Host "⚠ Could not auto-wire workshopNameSuffix into $parametersFile : $($_.Exception.Message)" -ForegroundColor Yellow
        Write-Host "  Manually add this to the parameters object:" -ForegroundColor DarkGray
        Write-Host '    "workshopNameSuffix": { "value": "${WORKSHOP_NAME_SUFFIX=}" }' -ForegroundColor DarkGray
    }
}

Write-Host ""
Write-Host "Next:" -ForegroundColor Cyan
Write-Host "  ..\workshop-scripts\preflight.ps1   # generate name salt + purge stale resources" -ForegroundColor DarkGray
Write-Host "  azd up --no-prompt                  # provision + deploy" -ForegroundColor DarkGray
